import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { UserRound, Pencil, Zap, Flame, Target, ChartNoAxesColumnIncreasing, Clock, Code, FileText, CircleCheck, CalendarDays, Trophy, Link as LinkIcon, Settings, ArrowRight, Layers, X, Shield } from 'lucide-react';
import useAuthStore from '../../stores/useAuthStore';
import useProgressStore from '../../stores/useProgressStore';
import { restoreSessionProgress } from '../../services/sessionProgress';
import { dashboardData, topicUrl } from '../dashboard/dashboardData';
import { progressData, studyTime } from '../progress/progressModel';
import './profile.css';
const defaults={bio:'',goal:'',weekly:10,links:[] as string[],publicBio:false,publicGoal:false,publicLinks:false};
function Card({title,subtitle,icon,action,children,className=''}:{title:string;subtitle?:string;icon:ReactNode;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`pr-card ${className}`}><header>{icon}<div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</header>{children}</section>}
function Meter({value}:{value:number}){return <div className="pr-meter" role="progressbar" aria-valuenow={Math.round(value)} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div>}
export default function ProfilePage(){
 const {user,token}=useAuthStore();const {progress,stats}=useProgressStore();const uid=String(user?.id||'guest');const key=`alvio-profile-${uid}`;
 const [extra,setExtra]=useState(defaults);const [remote,setRemote]=useState<any>(null);const [message,setMessage]=useState('');const [modal,setModal]=useState('');const [range,setRange]=useState(30);const [all,setAll]=useState(false);const [busy,setBusy]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 const [form,setForm]=useState({location:'',university:'',github:'',linkedin:'',avatar_url:''});const [link,setLink]=useState('');
 useEffect(()=>{try{setExtra({...defaults,...JSON.parse(localStorage.getItem(key)||'{}')})}catch{setExtra(defaults)};setRemote(null);if(progress?.userId!==uid)restoreSessionProgress(uid);if(!token)return;const abort=new AbortController();fetch('/api/profile',{headers:{Authorization:`Bearer ${token}`},signal:abort.signal}).then(r=>{if(!r.ok)throw Error('Unable to load account details. Please reload to retry.');return r.json()}).then(d=>{setRemote(d);setForm({location:d.user.location||'',university:d.user.university||'',github:d.user.github||'',linkedin:d.user.linkedin||'',avatar_url:d.user.avatar_url||''})}).catch(e=>{if(e.name!=='AbortError')setMessage(e.message)});return()=>abort.abort();},[uid,token]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close()},[modal]);
 function save(){try{localStorage.setItem(key,JSON.stringify(extra));setMessage('Saved on this device.');return true}catch{setMessage('Could not save. Device storage is unavailable.');return false}}
 async function saveAccount(){setBusy(true);try{if(!token)throw Error('Sign in to update your account.');const r=await fetch('/api/profile/update',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(form)});if(!r.ok)throw Error('Profile update failed. Please try again.');setRemote((d:any)=>({...d,user:{...d?.user,...form}}));useAuthStore.setState({user:{...user,...form,avatar:form.avatar_url} as any});save();setModal('');setMessage('Profile updated.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const base=dashboardData(progress?.userId===uid?progress:null,stats);const data=progress?.userId===uid?progressData(progress,stats,remote?.practiceActivity||[]):null;
 const name=remote?.user?.name||user?.name||'Learner';const avatar=remote?.user?.avatar_url||user?.avatar;const solved=remote?.solvedProblems||[];
 const cutoff=Date.now()-range*86400000;const recentSolved=solved.filter((p:any)=>Date.parse(p.solved_at)>=cutoff);const history=progress?.quizHistory||[];const journal=progress?.dailyActivity||{};
 const minutes=Object.entries(journal).filter(([date])=>Date.parse(date)>=cutoff).reduce((n,[,a])=>n+a.minutes,0);const quizzes=history.filter(q=>Date.parse(q.endedAt)>=cutoff).length;
 const activeDays=new Set([...Object.keys(journal).filter(d=>journal[d].sessions>0),...(remote?.activity||[]).map((a:any)=>a.created_at?.slice(0,10))].filter(Boolean)).size;
 const weekStart=data?.week[0]?.date||'';const weekly=solved.filter((p:any)=>p.solved_at?.slice(0,10)>=weekStart).length;const goalPercent=Math.min(100,weekly/Math.max(1,extra.weekly)*100);
 const skills=(all?base.topics:['array','linked-list','binary-tree','graph','hash-table'].map(id=>base.topics.find(t=>t.topicId===id)).filter(Boolean)) as typeof base.topics;
 const metrics=[[Zap,base.xp,'Total XP'],[Flame,activeDays,'Active Days'],[Target,solved.length,'Problems Solved'],[ChartNoAxesColumnIncreasing,progress?.quizTotals?.completed||history.length,'Quizzes Taken']] as const;
 return <div className="profile-page"><header className="pr-heading"><div><h1>My Profile</h1><p>Track your journey, showcase your skills, and stay motivated.</p></div><blockquote>“Discipline today.<br/>Extraordinary tomorrow.”<cite>— Alvio</cite></blockquote><div><button onClick={()=>setModal('edit')}><Pencil size={15}/>Edit Profile</button><button className="pr-text" onClick={()=>setModal('public')}>Preview Public Profile</button></div></header>
 {message&&<p className="pr-message" role="status">{message}<button aria-label="Dismiss message" onClick={()=>setMessage('')}><X size={14}/></button></p>}
 <section className="pr-card pr-summary"><div className="pr-identity"><div><div className="pr-avatar">{avatar?<img src={avatar} alt={`${name}'s avatar`}/>:<UserRound size={66}/>}</div><button className="pr-text" onClick={()=>setModal('edit')}><Pencil size={12}/> Edit</button></div><div><h2>{name}</h2><p>{remote?.user?.email||user?.email||'Sign in to sync your profile'}</p><span className="pr-rank"><Shield size={15}/>{base.rank}</span><p className="pr-quote">{extra.bio||'Learning today, building a better tomorrow.'}</p>{extra.goal&&<small>Learning goal · {extra.goal}</small>}</div></div><div className="pr-summary-right"><div className="pr-metrics">{metrics.map(([Icon,value,label])=><div key={label}><Icon/><span><strong>{value}</strong><small>{label}</small></span></div>)}</div><div className="pr-level"><span>Level Progress</span><strong>{Math.round(base.xpPercent)}%</strong></div><Meter value={base.xpPercent}/><p className="pr-next">Next level: {Math.max(0,base.nextXp-base.xp).toLocaleString()} XP remaining</p></div></section>
 <div className="pr-two"><Card title="Learning Overview" subtitle="A snapshot of your learning journey." icon={<ChartNoAxesColumnIncreasing/>} action={<select aria-label="Learning overview time range" value={range} onChange={e=>setRange(Number(e.target.value))}><option value={30}>Last 30 days</option><option value={7}>Last 7 days</option></select>}><div className="pr-overview">{[[Clock,studyTime(minutes),'Study Time'],[Code,recentSolved.length,'Problems Solved'],[FileText,quizzes,'Quizzes Taken'],[CircleCheck,base.topics.filter(t=>t.status==='completed'&&Date.parse(t.lastAccessed)>=cutoff).length,'Topics Completed']].map(([Icon,value,label]:any)=><div key={label}><Icon/><strong>{value}</strong><small>{label}</small></div>)}</div></Card>
 <Card title="Activity Calendar" subtitle="Your learning activity over the last 30 days." icon={<CalendarDays/>} action={<small>Last 30 days</small>}><div className="pr-calendar"><div><div className="pr-heat">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=><div key={d}><span>{d}</span>{Array.from({length:Math.ceil((30+(data?.heatmap[0]?.weekday||0))/7)},(_,w)=>{const cell=data?.heatmap.find((c,j)=>c.weekday===i&&Math.floor((j+(data.heatmap[0]?.weekday||0))/7)===w);return <span key={w} className={`pr-cell level-${Math.min(4,cell?.count||0)}`} title={cell?`${cell.date}: ${cell.count} activities`:'Outside date range'} style={{visibility:cell?'visible':'hidden'}}/>})}</div>)}</div><small className="pr-legend">Less <i/><i/><i/><i/> More</small></div><aside>Small<br/>steps<br/>every day<br/>lead to big<br/>results.</aside></div></Card></div>
 <div className="pr-three"><Card title="Skill Proficiency" subtitle="Your progress across key topics." icon={<Target/>} action={<button className="pr-text" onClick={()=>setAll(!all)}>{all?'Show Less':'View All'}</button>}><div className="pr-skills">{skills.map(t=><Link to={topicUrl(t)} key={t.topicId}><Layers size={18}/><span>{t.topicName}</span><Meter value={t.completionPercent}/><small>{t.completionPercent}%</small></Link>)}</div></Card>
 <Card title="Goals & Streaks" subtitle="Stay consistent, achieve more." icon={<Flame/>} action={<button className="pr-text" onClick={()=>setModal('goals')}>Set Goals</button>}><div className="pr-goal"><span>Current Streak<strong>{base.streak} {base.streak===1?'day':'days'}</strong></span><div className="pr-week">{data?.week.map(d=><span key={d.name}><i className={d.active?'done':''}>{d.active?'✓':''}</i><small>{d.name}</small></span>)}</div></div><div className="pr-goal"><Target/><div><strong>Weekly Goal</strong><small>{weekly} / {extra.weekly} problems</small><Meter value={goalPercent}/></div><small>{Math.round(goalPercent)}%</small></div></Card>
 <Card title="Recent Achievements" icon={<Trophy/>} action={<Link className="pr-text" to="/dashboard#achievements">View All</Link>}>{base.badges.length?<div className="pr-badges">{base.badges.slice(-3).reverse().map(b=><p key={b.id}><Trophy/><span><strong>{b.name}</strong><small>{b.description}</small></span></p>)}</div>:<div className="pr-empty"><Trophy size={42}/><strong>No achievements yet</strong><p>Keep learning and solving problems<br/>to earn your first achievement!</p></div>}</Card></div>
 <div className="pr-bottom"><Card title="About Me" subtitle="Tell the community a bit about yourself." icon={<UserRound/>}><div className="pr-bio"><textarea aria-label="About me" maxLength={400} placeholder="Share your learning goals, interests, or a short bio..." value={extra.bio} onChange={e=>setExtra({...extra,bio:e.target.value})}/><button onClick={save}>Save</button></div></Card><Card title="Quick Links" subtitle="Add your social links." icon={<LinkIcon/>}>{[...new Set([form.github,form.linkedin,...extra.links].filter(Boolean))].map(url=><a className="pr-social" key={url} href={/^https?:\/\//i.test(url)?url:undefined} target="_blank" rel="noreferrer">{url}</a>)}<button className="pr-wide" onClick={()=>setModal('links')}>+ Add Link</button></Card><Card title="Account Settings" subtitle="Manage your account preferences." icon={<Settings/>}><button className="pr-wide" onClick={()=>setModal('settings')}>Open Settings <ArrowRight size={16}/></button></Card></div>
 <dialog ref={dialog} className="pr-dialog" onCancel={()=>setModal('')} onClick={e=>{if(e.target===dialog.current)setModal('')}}><button className="pr-close" aria-label="Close dialog" onClick={()=>setModal('')}><X/></button><h2>{({edit:'Edit Profile',public:'Public Profile Preview',goals:'Learning Goals',links:'Your Links',settings:'Account Settings'} as Record<string,string>)[modal]}</h2>
 {modal==='edit'&&<form onSubmit={e=>{e.preventDefault();saveAccount()}}>{Object.entries(form).map(([field,value])=><label key={field}>{field.replace('_url',' URL')}<input type={['github','linkedin','avatar_url'].includes(field)?'url':'text'} value={value} maxLength={500} onChange={e=>setForm({...form,[field]:e.target.value})}/></label>)}<label>Learning Goal<input value={extra.goal} maxLength={100} onChange={e=>setExtra({...extra,goal:e.target.value})}/></label><button disabled={busy}>{busy?'Saving…':'Save Profile'}</button></form>}
 {modal==='goals'&&<form onSubmit={e=>{e.preventDefault();if(save())setModal('')}}><label>Weekly problems goal<input type="number" min={1} max={200} required value={extra.weekly} onChange={e=>setExtra({...extra,weekly:Number(e.target.value)})}/></label><label>Learning Goal<input maxLength={100} value={extra.goal} onChange={e=>setExtra({...extra,goal:e.target.value})}/></label><button>Save Goals</button></form>}
 {modal==='links'&&<form onSubmit={e=>{e.preventDefault();if(!/^https?:\/\//i.test(link))return;const next={...extra,links:[...new Set([...extra.links,link])].slice(0,4)};setExtra(next);localStorage.setItem(key,JSON.stringify(next));setLink('');setModal('')}}><label>GitHub, LinkedIn, portfolio, or personal site<input type="url" required placeholder="https://" value={link} onChange={e=>setLink(e.target.value)}/></label>{extra.links.map(url=><p key={url}>{url}<button type="button" onClick={()=>{const next={...extra,links:extra.links.filter(v=>v!==url)};setExtra(next);localStorage.setItem(key,JSON.stringify(next))}}>Remove</button></p>)}<button>Add Link</button></form>}
 {modal==='settings'&&<form onSubmit={e=>{e.preventDefault();if(save())setModal('')}}><p>Public preview visibility</p>{(['publicBio','publicGoal','publicLinks'] as const).map(k=><label className="pr-check" key={k}><input type="checkbox" checked={extra[k]} onChange={e=>setExtra({...extra,[k]:e.target.checked})}/>{k.replace('public','Show ')}</label>)}<p>Bio, goals, links, and visibility preferences are saved on this device. Email and learning history remain private.</p><button>Save Preferences</button></form>}
 {modal==='public'&&<div className="pr-public">{avatar&&<img src={avatar} alt="Profile avatar"/>}<h3>{name}</h3>{extra.publicBio&&<p>{extra.bio}</p>}{extra.publicGoal&&<p>{extra.goal}</p>}{extra.publicLinks&&extra.links.map(url=><a key={url} href={/^https?:\/\//i.test(url)?url:undefined}>{url}</a>)}<small>This is a private preview; it does not publish your profile.</small></div>}
 {message&&<p role="status">{message}</p>}</dialog></div>;
}
