import { useEffect, useRef, useState } from 'react';
import useAuthStore from '../../stores/useAuthStore';
export type InterviewMessage={role:'interviewer'|'candidate';content:string;timestamp:Date};
export type AnswerReview={score:number|null;summary:string;criteria:{label:string;status:string;detail:string}[];tip:string};
const unavailable='Interview service temporarily unavailable. Please try again in a moment. Your current answer has been preserved.';
export function useInterviewSession(){
 const [topic,setTopic]=useState('Arrays & HashMaps'),[difficulty,setDifficulty]=useState('Medium');
 const [started,setStarted]=useState(false),[busy,setBusy]=useState(false),[finishing,setFinishing]=useState(false);
 const [messages,setMessages]=useState<InterviewMessage[]>([]),[input,setInput]=useState(''),[notes,setNotes]=useState('');
 const [review,setReview]=useState<AnswerReview|null>(null),[next,setNext]=useState(''),[evaluation,setEvaluation]=useState<string|null>(null);
 const [camera,setCamera]=useState(true),[mic,setMic]=useState(true),[voice,setVoice]=useState(true),[feedback,setFeedback]=useState(false);
 const [stream,setStream]=useState<MediaStream|null>(null),[deviceError,setDeviceError]=useState(''),[error,setError]=useState('');
 const [listening,setListening]=useState(false),[interim,setInterim]=useState(''),[speaking,setSpeaking]=useState(false),[elapsed,setElapsed]=useState(0);
 const [online,setOnline]=useState(navigator.onLine);const rec=useRef<any>(null),abort=useRef<AbortController|null>(null),lock=useRef(false),retry=useRef<()=>void>(()=>{}),sessionStart=useRef(0);
 const question=Math.max(1,messages.filter(m=>m.role==='interviewer').length),total=8;
 useEffect(()=>{const yes=()=>setOnline(true),no=()=>setOnline(false);window.addEventListener('online',yes);window.addEventListener('offline',no);return()=>{window.removeEventListener('online',yes);window.removeEventListener('offline',no)}},[]);
 useEffect(()=>{if(!started||evaluation||finishing)return;const id=setInterval(()=>setElapsed(Math.floor((Date.now()-sessionStart.current)/1000)),1000);return()=>clearInterval(id)},[started,evaluation,finishing]);
 useEffect(()=>{let disposed=false,owned:MediaStream|null=null;if(started&&camera&&!evaluation&&!finishing){if(!navigator.mediaDevices?.getUserMedia){setCamera(false);setDeviceError('Camera unavailable. Video is disabled for this session.')}else navigator.mediaDevices.getUserMedia({video:true,audio:false}).then(s=>{if(disposed){s.getTracks().forEach(t=>t.stop());return}owned=s;setStream(s)}).catch(()=>{if(!disposed){setCamera(false);setDeviceError('Camera unavailable. Video is disabled for this session.')}})}else setStream(null);return()=>{disposed=true;owned?.getTracks().forEach(t=>t.stop())}},[started,camera,evaluation,finishing]);
 useEffect(()=>{const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){setDeviceError('Microphone dictation unavailable. You can continue by typing.');return}const recognition=new Speech();recognition.continuous=true;recognition.interimResults=true;recognition.lang='en-US';recognition.onresult=(e:any)=>{let partial='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript;if(e.results[i].isFinal)setInput(s=>(s+' '+text).trim());else partial+=text}setInterim(partial)};recognition.onend=()=>{setListening(false);setInterim('')};recognition.onerror=()=>{setListening(false);setDeviceError('Microphone unavailable. You can continue by typing.')};rec.current=recognition;return()=>{recognition.abort();rec.current=null}},[]);
 useEffect(()=>{if(!mic||finishing||evaluation){rec.current?.stop();setListening(false)}},[mic,finishing,evaluation]);
 useEffect(()=>()=>{abort.current?.abort();window.speechSynthesis?.cancel()},[]);
 useEffect(()=>{if(!voice){window.speechSynthesis?.cancel();setSpeaking(false)}},[voice]);
 function speak(text:string){if(!voice||!window.speechSynthesis)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text.replace(/[*#`]/g,''));utterance.onstart=()=>setSpeaking(true);utterance.onend=utterance.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(utterance)}
 function dictate(){if(listening){rec.current?.stop();return}if(!rec.current||!mic){setDeviceError('Microphone unavailable or off. You can continue by typing.');return}try{window.speechSynthesis?.cancel();rec.current.start();setListening(true)}catch{setDeviceError('Microphone unavailable. You can continue by typing.')}}
 async function chat(system:string,history:{role:string;content:string}[]){const controller=new AbortController();abort.current=controller;const timer=setTimeout(()=>controller.abort(),45000);try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({messages:[{role:'system',content:system},...history]})});if(!response.ok)throw Error('Interview API status '+response.status);const data=await response.json();if(typeof data.text!=='string'||!data.text.trim()||/GROQ_API_KEY|api.key.*configur|stack trace|process\.env/i.test(data.text))throw Error('Invalid interview service response');return data.text}catch(e){console.error('Interview request failed',e);throw e}finally{clearTimeout(timer)}}
 async function start(){if(lock.current)return;lock.current=true;setStarted(true);setBusy(true);setError('');setMessages([]);setReview(null);setNext('');setEvaluation(null);setInput('');setNotes('');setElapsed(0);sessionStart.current=Date.now();retry.current=start;try{const text=await chat(`You are a professional technical interviewer. Topic: ${topic}. Difficulty: ${difficulty}. This interview has ${total} questions. Greet the candidate and ask exactly one clear first question. Do not reveal the answer. Output only interview dialogue.`,[{role:'user',content:'Begin the interview.'}]);setMessages([{role:'interviewer',content:text,timestamp:new Date()}]);speak(text)}catch{setError(unavailable)}finally{lock.current=false;setBusy(false)}}
 async function submit(){if(lock.current||next||review||!input.trim()||!messages.length)return;lock.current=true;setBusy(true);setError('');rec.current?.stop();const answer=input.trim();const candidate:InterviewMessage={role:'candidate',content:answer,timestamp:new Date()};const transcript=[...messages,candidate];retry.current=submit;try{const text=await chat(`You are a professional technical interview evaluator. Topic: ${topic}. Difficulty: ${difficulty}. Evaluate only the candidate's latest answer against the latest question. Return valid JSON, no markdown: {"score":number from 0 to 100,"summary":"brief evidence-based assessment","criteria":[{"label":"question-specific criterion","status":"strong or partial or needs-improvement","detail":"brief evidence"}],"tip":"one actionable tip","nextQuestion":"one relevant follow-up or new question, adapting difficulty to the answer"}. Do not expose answers to future questions. ${feedback?'Include a short live coaching suggestion.':'Keep feedback limited to the submitted answer.'} This is question ${question} of ${total}.`,transcript.map(m=>({role:m.role==='candidate'?'user':'assistant',content:m.content})));const parsed=JSON.parse(text.replace(/^\s*```(?:json)?/,'').replace(/```\s*$/,''));if(typeof parsed.nextQuestion!=='string'||!parsed.nextQuestion.trim()||typeof parsed.summary!=='string')throw Error('Invalid evaluation structure');setMessages(transcript);setInput(current=>current.trim()===answer?"":current);setReview({score:typeof parsed.score==='number'&&Number.isFinite(parsed.score)&&parsed.score>=0&&parsed.score<=100?Math.round(parsed.score):null,summary:parsed.summary,criteria:Array.isArray(parsed.criteria)?parsed.criteria.filter((c:any)=>typeof c.label==='string'&&typeof c.detail==='string').slice(0,5):[],tip:typeof parsed.tip==='string'?parsed.tip:''});setNext(parsed.nextQuestion)}catch(e){console.error('Answer evaluation unavailable',e);setError(unavailable)}finally{lock.current=false;setBusy(false)}}
 function advance(){if(!next||busy||question>=total)return;setMessages(m=>[...m,{role:'interviewer',content:next,timestamp:new Date()}]);speak(next);setNext('');setReview(null);setInput('')}
 async function finish(){if(lock.current)return;lock.current=true;setFinishing(true);setError('');rec.current?.stop();window.speechSynthesis?.cancel();retry.current=finish;try{const report=await chat(`Evaluate this ${topic} (${difficulty}) technical interview. Generate a constructive markdown report: Overall Score, Technical Knowledge, Problem Solving, Communication, Clarity, Complexity Analysis, Strengths, Areas to Improve, Recommended Practice, and Review Answers. Assess only evidence in the transcript. For missing evidence write Not assessed; do not invent performance or confidence scores. The session may be partial.`,[{role:'user',content:messages.map(m=>`${m.role}: ${m.content}`).join('\n\n')||'No answers were completed; report not assessed.'}]);setEvaluation(report);const key='alvio-interviews-'+(useAuthStore.getState().user?.id||'guest');try{const saved=JSON.parse(localStorage.getItem(key)||'[]');localStorage.setItem(key,JSON.stringify([{date:new Date().toISOString(),topic,difficulty,duration:elapsed,report,transcript:messages},...saved].slice(0,20)))}catch{setError('Report is ready, but could not be saved on this device.')}}catch{setError('Your answers are preserved. The report service is temporarily unavailable. Please retry.')}finally{lock.current=false;setFinishing(false)}}
 function reset(){abort.current?.abort();rec.current?.stop();window.speechSynthesis?.cancel();setStarted(false);setEvaluation(null);setMessages([]);setReview(null);setNext('');setInput('');setNotes('');setError('')}
 return {topic,setTopic,difficulty,setDifficulty,started,busy,finishing,messages,input,setInput,notes,setNotes,review,next,evaluation,camera,setCamera,mic,setMic,voice,setVoice,feedback,setFeedback,stream,deviceError,error,listening,interim,speaking,elapsed,online,question,total,start,submit,advance,finish,reset,dictate,retry:()=>retry.current()};
}
export type InterviewSession=ReturnType<typeof useInterviewSession>;


