import { useEffect, useRef, useState } from 'react';
import useAuthStore from '../../stores/useAuthStore';
import useProgressStore from '../../stores/useProgressStore';
export type TutorMessage={id:string;role:'user'|'assistant';content:string;rating?:'helpful'|'unhelpful'};
export type TutorChat={id:string;title:string;updatedAt:string;messages:TutorMessage[]};
export const welcome="👋 Hi! I’m your AI DSA tutor. I can explain concepts, debug code, answer questions, and help you prepare for interviews. What would you like to learn about?";
const fresh=():TutorChat=>({id:crypto.randomUUID(),title:'New conversation',updatedAt:new Date().toISOString(),messages:[]});
export function useTutor(){const uid=useAuthStore(s=>String(s.user?.id||'guest'));const key=`alvio-tutor-${uid}`;const [ownerKey,setOwnerKey]=useState(key);const [chat,setChat]=useState<TutorChat>(fresh),[history,setHistory]=useState<TutorChat[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState('Teach me'),[attachment,setAttachment]=useState<{name:string;text:string}|null>(null),[notice,setNotice]=useState(''),[listening,setListening]=useState(false);const abort=useRef<AbortController|null>(null),lock=useRef(false),recognition=useRef<any>(null),loadedKey=useRef(''),last=useRef<{messages:TutorMessage[];prompt:string}|null>(null);
 useEffect(()=>{abort.current?.abort();abort.current=null;recognition.current?.abort();last.current=null;lock.current=false;setBusy(false);setInput('');setAttachment(null);setError('');try{const stored=JSON.parse(localStorage.getItem(key)||'[]');setHistory(Array.isArray(stored)?stored:[])}catch{setHistory([])}setChat(fresh());setOwnerKey(key);loadedKey.current=key;return()=>abort.current?.abort()},[key]);
 function persist(items:TutorChat[]){try{localStorage.setItem(key,JSON.stringify(items.slice(0,30)))}catch{setNotice('Conversation history could not be saved on this device.')}}
 useEffect(()=>{if(ownerKey!==key||loadedKey.current!==key||!chat.messages.length)return;const timer=setTimeout(()=>{setHistory(items=>{const next=[chat,...items.filter(c=>c.id!==chat.id)];persist(next);return next})},250);return()=>clearTimeout(timer)},[chat,key,ownerKey]);
 useEffect(()=>()=>{recognition.current?.abort();abort.current?.abort()},[]);
 function archive(){if(chat.messages.length){const next=[chat,...history.filter(c=>c.id!==chat.id)];setHistory(next);persist(next)}}
 function newChat(){abort.current?.abort();abort.current=null;lock.current=false;setBusy(false);archive();setChat(fresh());setInput('');setError('');setAttachment(null);last.current=null;recognition.current?.stop()}
 function open(c:TutorChat){abort.current?.abort();abort.current=null;lock.current=false;setBusy(false);recognition.current?.stop();archive();setChat(c);setInput('');setError('');setAttachment(null);last.current=null}
 function rename(id:string,title:string){const clean=title.trim().slice(0,80);if(!clean)return;const next=history.map(c=>c.id===id?{...c,title:clean}:c);setHistory(next);persist(next);if(chat.id===id)setChat(c=>({...c,title:clean}))}
 function remove(id:string){const next=history.filter(c=>c.id!==id);setHistory(next);persist(next);if(chat.id===id){abort.current?.abort();abort.current=null;lock.current=false;setBusy(false);setChat(fresh());setInput('');setError('');last.current=null}}
 function rate(id:string,rating:'helpful'|'unhelpful'){setChat(c=>({...c,messages:c.messages.map(m=>m.id===id?{...m,rating}:m)}))}
 async function request(messages:TutorMessage[],prompt:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');const controller=new AbortController();abort.current=controller;const assistantId=crypto.randomUUID();const id=chat.id;setChat(c=>({...c,updatedAt:new Date().toISOString(),title:c.messages.length?c.title:prompt.slice(0,65),messages:[...messages,{id:assistantId,role:'assistant',content:''}]}));last.current={messages,prompt};let result='';const update=()=>setChat(c=>c.id!==id?c:{...c,messages:c.messages.map(m=>m.id===assistantId?{...m,content:result}:m)});const timer=setTimeout(()=>controller.abort('timeout'),90000);
 try{const progress=useProgressStore.getState().progress;const context=progress?.userId===uid?{weakTopics:progress.weakAreas.slice(0,3),completed:progress.topics.filter(t=>t.status==='completed').map(t=>t.topicName).slice(0,6)}:{};
 const directives:Record<string,string>={'Teach me':'Teach with clear examples and manageable steps.','Give me a hint':'Give one progressive hint. Do not reveal the full solution or solution code unless explicitly requested.','Quiz me':'Ask one question at a time and wait for my answer before explaining.','Review my code':'Review correctness, edge cases and complexity. Explain issues before proposing fixes.'};
 const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({tutorMode:mode,messages:[...messages.slice(-20).map(m=>({role:m.role,content:m.content})),{role:'user',content:`Tutoring preference: ${directives[mode]} Relevant learning context: ${JSON.stringify(context)}. Apply this to my preceding request; do not repeat this metadata.`}]})});if(!response.ok)throw Error(`Tutor HTTP ${response.status}`);
 if(response.headers.get('content-type')?.includes('text/event-stream')){if(!response.body)throw Error('Missing response stream');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';function event(raw:string){const line=raw.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n');if(!line||line==='[DONE]')return;const payload=JSON.parse(line);if(payload.error)throw Error('Tutor stream error');if(typeof payload.delta==='string'){result+=payload.delta;update()}else if(payload.done&&typeof payload.text==='string'&&!result){result=payload.text;update()}}
 while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});buffer=buffer.replace(/\r\n/g,'\n');let boundary;while((boundary=buffer.indexOf('\n\n'))>=0){event(buffer.slice(0,boundary));buffer=buffer.slice(boundary+2)}}buffer+=decoder.decode();if(buffer.trim())event(buffer);
 }else{const payload=await response.json();if(typeof payload.text!=='string')throw Error('Invalid tutor response');result=payload.text;update()}
 if(!result.trim())throw Error('Empty tutor response');if(/GROQ_API_KEY|process\.env|api.key.*(?:missing|configur)/i.test(result)){result='';update();throw Error('Provider configuration response')}
 }catch(e){if(abort.current!==controller)return;if(controller.signal.aborted&&controller.signal.reason!=='timeout'){setNotice('Response stopped.')}else{console.error('Tutor request failed',e);setError('AI Tutor is temporarily unavailable. Please try again in a moment.')}}finally{clearTimeout(timer);if(abort.current===controller){lock.current=false;setBusy(false)}}}
 function send(text=input){if(lock.current||(!text.trim()&&!attachment))return;const content=text.trim()+(attachment?`\n\nAttached text file: ${attachment.name}\n\n${attachment.text}`:'');const messages=[...chat.messages.filter(m=>m.content),{id:crypto.randomUUID(),role:'user' as const,content}];setInput('');setAttachment(null);recognition.current?.stop();request(messages,content)}
 function retry(){if(last.current)request(last.current.messages,last.current.prompt)}
 function dictate(){if(listening){recognition.current?.stop();return}const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){setNotice('Voice input unavailable. You can continue by typing.');return}const rec=new Speech();recognition.current=rec;rec.continuous=false;rec.interimResults=false;rec.onresult=(e:any)=>setInput(s=>(s+' '+e.results[0][0].transcript).trim());rec.onend=()=>setListening(false);rec.onerror=()=>{setListening(false);setNotice('Voice input unavailable. You can continue by typing.')};try{rec.start();setListening(true)}catch{setNotice('Voice input unavailable. You can continue by typing.')}}
 return {chat,history,input,setInput,busy,error,mode,setMode,attachment,setAttachment,notice,setNotice,listening,newChat,open,rename,remove,rate,send,retry,dictate,stop:()=>abort.current?.abort()};}
