// Requires Playwright; uses isolated mocked auth responses, not real accounts.
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE || 'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'});const p=await b.newPage({viewport:{width:1536,height:1024},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://127.0.0.1:3001/auth?mode=login&next=%2Fdashboard%3Fsource%3Dauth%23learning');await p.getByRole('heading',{name:'Welcome back',exact:true}).waitFor();await p.screenshot({path:'data/auth-login-desktop.png'});
await p.getByLabel('Password',{exact:true}).fill('example-password');await p.getByRole('button',{name:'Show password',exact:true}).click();assert.equal(await p.getByLabel('Password',{exact:true}).getAttribute('type'),'text');await p.getByRole('button',{name:'Hide password',exact:true}).click();assert.equal(await p.getByLabel('Password',{exact:true}).getAttribute('type'),'password');
await p.getByRole('button',{name:'Forgot password?',exact:true}).click();await p.getByRole('dialog').waitFor();await p.keyboard.press('Escape');assert.equal(await p.locator('dialog').evaluate(e=>e.open),false);
await p.route('**/api/auth/login',r=>r.fulfill({status:401,contentType:'application/json',body:JSON.stringify({error:'Incorrect email or password.'})}));await p.getByLabel('Email',{exact:true}).fill('preview@example.test');await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.getByRole('alert').waitFor();assert.equal(await p.getByRole('alert').innerText(),'Incorrect email or password.');assert.equal(await p.getByRole('alert').evaluate(e=>e===document.activeElement),true);await p.unroute('**/api/auth/login');
await p.getByRole('link',{name:'Create an account',exact:true}).click();await p.getByRole('heading',{name:'Join Alvio',exact:true}).waitFor();assert.equal(new URL(p.url()).searchParams.get('next'),'/dashboard?source=auth#learning');assert.equal(await p.locator('[role="alert"]').count(),0);await p.screenshot({path:'data/auth-signup-desktop.png'});
for(const width of [768,390,360]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===390)await p.screenshot({path:'data/auth-signup-mobile.png'});}
for(const mode of ['signup','login']){await p.goto(`http://127.0.0.1:3001/auth?mode=${mode}&next=%2Fdashboard%3Fsource%3Dauth%23learning`);await p.getByLabel('Email',{exact:true}).fill('preview@example.test');await p.getByLabel('Password',{exact:true}).fill('test-only-password');if(mode==='signup')await p.getByLabel('Full name',{exact:true}).fill('Preview Student');await p.route(`**/api/auth/${mode}`,r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({user:{id:`auth-ui-${mode}`,name:'Preview Student',email:'preview@example.test'},token:'isolated-preview'})}));await p.getByRole('button',{name:mode==='signup'?'Create account':'Sign in',exact:true}).click();await p.waitForURL('**/dashboard?source=auth#learning');await p.locator('.ad-page').waitFor();await p.unroute(`**/api/auth/${mode}`);}
assert.deepEqual(errors,[]);console.log('Auth UI passed: desktop/mobile, modes, query/hash retention, visibility, help dialog, accessible inline errors, successful login/signup redirects with isolated test responses.');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
