const {chromium}=require('C:/Users/Abhiram/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage();page.on('pageerror',e=>failures.push({pageError:e.stack,route:page.url()}));
const routes=[['/dashboard','dashboard','dashboard'],['/learn','learn','map'],['/learn/data-structures','learn','structures'],['/learn/heap','learn','structures'],['/learn/array','learn','structures'],['/learn/linked-list','learn','structures'],['/learn/algorithms','learn','algorithms'],['/learn/algorithms/merge-sort','learn','algorithms'],['/learn/complexity','learn','complexity'],['/video-learning','learn','videos'],['/3d-visualizer?ds=Heap','learn','structures3d'],['/algorithms-visualizer?algo=merge-sort','learn','algorithms3d'],['/coding','practice','playground'],['/quiz','practice','quiz'],['/ai-tutor','ai','tutor'],['/learn/ai-visualizer','ai','aiVisualizer']];
let failures=[];for(const [width,height] of [[1920,1080],[1536,864],[1440,900],[1366,768],[1280,800],[1024,768],[768,1024],[390,844]]){await page.setViewportSize({width,height});for(const [route,section,active] of routes){await page.goto('http://localhost:3001'+route);await page.locator('.app-main').waitFor();await page.waitForTimeout(300);let m=await page.evaluate(()=>{const rect=s=>{const r=document.querySelector(s).getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}};return {header:rect('.app-header'),sidebar:rect('.app-sidebar'),main:rect('.app-main'),logo:rect('.app-brand'),container:rect('.app-page-container'),padding:getComputedStyle(document.querySelector('.app-page-container')).paddingLeft,overflow:document.documentElement.scrollWidth>innerWidth+1,global:document.querySelector('.app-sections [aria-current]')?.dataset.section,active:document.querySelector('.app-sidebar [data-nav-id][aria-current]')?.dataset.navId}});try{assert.equal(m.header.height,64);assert.equal(m.global,section);assert.equal(m.active,active);assert.equal(m.main.x,width>=1024?240:0);if(width>=1024){assert.equal(m.sidebar.width,240);assert.equal(m.sidebar.y,64);assert.equal(m.logo.x,20)}assert.equal(m.padding,width<=600?'14px':width<=1000?'18px':'24px');assert.equal(m.overflow,false,JSON.stringify(m));}catch(e){failures.push({width,route,error:e.message});} }console.log('Viewport complete',width,failures.length)}

await page.setViewportSize({width:1440,height:900});await page.goto('http://localhost:3001/dashboard');await page.locator('.app-header').waitFor();
await page.evaluate(()=>document.querySelector('.app-header').dataset.identity='persistent');
for(const selector of ['.app-sections a[data-section="learn"]','[data-nav-id="structures"]','a[href="/learn/heap"]','.learning-action-strip a[href="/3d-visualizer?ds=Heap"]','.app-sections a[data-section="practice"]','[data-nav-id="quiz"]','.app-sections a[data-section="ai"]']){
 await page.locator(selector).first().click();await page.waitForTimeout(400);assert.equal(await page.locator('.app-header').getAttribute('data-identity'),'persistent','Shell remounted during navigation');assert.equal(await page.locator('.app-header').evaluate(e=>e.getBoundingClientRect().height),64);
}
await page.keyboard.press('Control+k');const search=page.getByRole('combobox',{name:'Search Alvio'});await search.fill('heap');await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');await page.waitForURL('**/learn/heap');await page.locator('.learning-action-strip').waitFor();assert.equal(await page.locator('.learning-action-strip a').count(),3,'Heap must not advertise an unsupported quiz');
await page.keyboard.press('Control+k');await search.fill('heap');await page.keyboard.press('ArrowUp');await page.keyboard.press('Enter');await page.waitForURL('**/ai-tutor*');await page.waitForFunction(()=>document.querySelector('textarea[aria-label="Message AI Tutor"]')?.value==='Explain heap');assert.equal(await page.locator('.tt-message.user').count(),0,'Search must prefill, not send');
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Open navigation',exact:true}).click();assert.equal(await page.locator('.app-main').getAttribute('inert'),'');assert.equal(await page.locator('.app-header').getAttribute('inert'),'');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.closest('.app-sidebar')!==null),true);await page.keyboard.press('Tab');await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Open navigation',exact:true}).evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('.app-main').getAttribute('inert'),null);
await page.goto('http://localhost:3001/learn/heap');await page.locator('.learning-action-strip').waitFor();await page.screenshot({path:'data/navigation-mobile.png'});
await page.setViewportSize({width:1440,height:900});await page.goto('http://localhost:3001/learn/algorithms');await page.locator('.al-hub').waitFor();await page.screenshot({path:'data/navigation-desktop.png'});
console.log(JSON.stringify(failures,null,2));await browser.close();if(failures.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
