// Run against the local app. Uses all real API problem data; account responses are isolated fixtures.
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE || 'C:/Users/Abhiram/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const url=process.env.ALVIO_URL || 'http://localhost:3001';
(async()=>{
 const b=await chromium.launch({headless:true,channel:'msedge'});
 const p=await b.newPage({viewport:{width:1273,height:837},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 const response=await p.request.get(url+'/api/problems');assert(response.ok());const all=await response.json();assert(all.length>=472);
 const saved=new Set([all[1].id]);let solved=[{id:all[0].id}];
 await p.addInitScript(()=>localStorage.setItem('alvio-auth-storage',JSON.stringify({state:{user:{id:'practice-test',name:'Alex'},token:'isolated-test',isAuthenticated:true},version:0})));
 await p.route('**/api/profile',r=>r.fulfill({json:{solvedProblems:solved,attemptedProblems:[{id:all[0].id},{id:all[1].id}]}}));
 await p.route('**/api/profile/favourites',r=>r.fulfill({json:[...saved].map(problem_id=>({problem_id}))}));
 await p.route('**/api/problems/*/interaction',r=>{if(r.request().method()==='POST'){const body=r.request().postDataJSON();assert.equal(body.type,'star');assert(['add','remove'].includes(body.action));const id=r.request().url().split('/').at(-2);body.action==='add'?saved.add(id):saved.delete(id);return r.fulfill({json:{success:true}});}return r.fulfill({json:{liked:false,disliked:false,starred:false}});});
 await p.goto(url+'/coding');await p.locator('.problem-row').first().waitFor();assert.equal(await p.locator('.problem-row').count(),25);assert.equal(await p.locator('.practice-stats>div').last().locator('strong').innerText(),String(all.length));await p.locator('.problem-status.solved').waitFor();assert.equal(await p.locator('.problem-status.attempted').count(),1);
 await p.screenshot({path:'data/practice-desktop.png'});
 const search=p.getByRole('searchbox',{name:'Search problems'});await search.fill('linked list');await p.waitForURL('**q=linked+list');await p.waitForTimeout(250);assert((await p.locator('.problem-row').count())>0);assert((await p.locator('.problem-tags').allTextContents()).every(t=>t.toLowerCase().includes('linked list')));
 await search.fill('no-such-problem-xyz');await p.getByRole('heading',{name:'No problems found'}).waitFor();await p.getByRole('button',{name:'Clear filters'}).click();await p.locator('.problem-row').first().waitFor();
 await p.getByRole('button',{name:'Arrays',exact:true}).click();await p.waitForTimeout(100);assert.equal(await p.getByRole('button',{name:'Arrays',exact:true}).getAttribute('aria-pressed'),'true');await p.getByRole('button',{name:'All',exact:true}).click();
 await p.getByRole('button',{name:'Filters',exact:true}).click();await p.getByLabel('Difficulty',{exact:true}).selectOption('Easy');await p.getByRole('button',{name:'Apply Filters'}).click();await p.waitForTimeout(200);assert((await p.locator('.problem-difficulty').allTextContents()).every(d=>d==='Easy'));
 await p.getByRole('button',{name:/^Filters/}).click();await p.getByRole('button',{name:'Reset',exact:true}).click();await p.getByLabel('Status',{exact:true}).selectOption('Attempted');await p.getByRole('button',{name:'Apply Filters'}).click();await p.waitForTimeout(200);await p.waitForFunction(()=>document.querySelectorAll('.problem-row').length===1);assert.equal(await p.locator('.problem-row').count(),1);assert.equal(await p.locator('.problem-title').innerText(),all[1].title);
 await p.getByRole('button',{name:/^Filters/}).click();await p.getByRole('button',{name:'Reset',exact:true}).click();await p.keyboard.press('Escape');
 await p.getByLabel('Sort problems').selectOption('Difficulty');await p.waitForTimeout(150);assert((await p.locator('.problem-difficulty').allTextContents()).every(d=>d==='Easy'));
 await p.getByLabel('Sort problems').selectOption('Recently Added');await p.waitForTimeout(150);assert.equal(await p.locator('.problem-title').first().innerText(),all.at(-1).title);
 await p.getByLabel('Sort problems').selectOption('Most Attempted');await p.waitForTimeout(150);assert.equal(await p.locator('.problem-title').first().innerText(),[...all].sort((a,b)=>b.submissions-a.submissions)[0].title);
 await p.getByLabel('Sort problems').selectOption('Acceptance Rate');await p.getByLabel('Sort problems').selectOption('Most Relevant');
 await p.getByRole('button',{name:'Page 2',exact:true}).click();await p.waitForTimeout(150);assert.equal(await p.locator('.problem-title').first().innerText(),all[25].title);const listUrl=p.url();
 await p.locator('.problem-row-link').first().focus();await p.keyboard.press('Enter');await p.locator('.practice-workspace').waitFor();assert.equal(new URL(p.url()).searchParams.get('problem'),all[25].id);await p.goBack();await p.locator('.problem-row').first().waitFor();assert.equal(p.url(),listUrl);assert.equal(await p.getByRole('button',{name:'Page 2',exact:true}).getAttribute('aria-current'),'page');
 await p.locator('.problem-row-link').first().click();await p.locator('.practice-workspace').waitFor();solved=[...solved,{id:all[25].id}];await p.getByRole('button',{name:'Problem List',exact:true}).click();await p.locator('.problem-row').first().waitFor();await p.locator('.problem-status.solved').first().waitFor();assert.equal(new URL(p.url()).searchParams.get('page'),'2');await p.getByRole('button',{name:'Page 1',exact:true}).click();await p.getByRole('button',{name:`Bookmark ${all[0].title}`,exact:true}).click();await p.getByRole('link',{name:'Bookmarks',exact:true}).click();await p.waitForTimeout(200);assert.equal(await p.locator('.problem-row').count(),2);await p.getByRole('button',{name:`Remove bookmark for ${all[0].title}`,exact:true}).click();await p.waitForFunction(()=>document.querySelectorAll('.problem-row').length===1);assert.equal(await p.locator('.problem-row').count(),1);
 await p.getByRole('link',{name:'Coding Playground',exact:true}).click();await p.getByRole('button',{name:'Notifications',exact:true}).click();await p.getByText("You're all caught up").waitFor();await p.keyboard.press('Escape');
 await p.keyboard.press('Control+k');assert.equal(await p.getByRole('textbox',{name:'Search anything'}).evaluate(el=>el===document.activeElement),true);await p.getByRole('textbox',{name:'Search anything'}).fill('matrix');await p.keyboard.press('Enter');await p.waitForURL('**q=matrix');await p.locator('.problem-row').first().waitFor();
 for(const width of [1536,1024,768,390,360]){await p.setViewportSize({width,height:844});await p.goto(url+'/coding');await p.locator('.problem-row').first().waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await p.locator('.practice-main').evaluate(el=>el.scrollWidth<=el.clientWidth),`No main overflow at ${width}`);if(width===768)await p.screenshot({path:'data/practice-tablet.png'});if(width===390)await p.screenshot({path:'data/practice-mobile.png'});if(width<1024){await p.getByRole('button',{name:'Toggle navigation'}).click();await p.getByRole('link',{name:'Bookmarks',exact:true}).click();await p.waitForTimeout(200);await p.waitForFunction(()=>document.querySelectorAll('.problem-row').length===1);assert.equal(await p.locator('.problem-row').count(),1);}}
 assert.deepEqual(errors,[]);await b.close();console.log(`PASS: ${all.length} real problems; search, empty state, topic, difficulty/status filters, all sorts, pagination, keyboard problem navigation, back-state restoration, solved/attempted states, bookmark add/remove, global search, notifications, desktop/tablet/mobile overflow.`);
})().catch(e=>{console.error(e);process.exit(1)});



