const assert=require('node:assert/strict');const {load}=require('./visualizer-loader.cjs');const {validateSpecification,safePlatformUrl}=load('model');const {example}=load('example');
assert.equal(validateSpecification(example).steps.length,4);
for(const mutate of [s=>s.steps[0].afterState.edges[0].to='missing',s=>s.steps[0].codeLines=[999],s=>s.steps[1].beforeState.nodes[0].value=999,s=>s.steps[0].afterState.nodes.push({...s.steps[0].afterState.nodes[0]}),s=>s.structure='execute-javascript',s=>s.steps[0].operation='eval',s=>s.steps[0].afterState.nodes[0].value=Infinity,s=>s.steps[0].afterState.nodes[0].label={html:'<script>'}]){const s=JSON.parse(JSON.stringify(example));mutate(s);assert.throws(()=>validateSpecification(s));}
assert.equal(safePlatformUrl('javascript:alert(1)'),null);assert.equal(safePlatformUrl('https://leetcode.com.evil.test/problems/a'),null);assert.equal(safePlatformUrl('https://leetcode.com/problems/two-sum/'),'https://leetcode.com/problems/two-sum/');
console.log('PASS bounded schema, edges, duplicate IDs, continuity, code synchronization, untrusted types, URL allowlist');

const {compileSpecification,adapters}=load('model');const wire=JSON.parse(JSON.stringify(example));wire.initialState=wire.steps[0].beforeState;wire.steps=wire.steps.map(({beforeState,codeLines,...s})=>({...s,codeFocus:codeLines.map(n=>wire.code.split('\n')[n-1].trim())}));assert.deepEqual(compileSpecification(wire),example);wire.steps[0].codeFocus=['not in code'];assert.throws(()=>compileSpecification(wire));
const {layout}=load('renderers/layout');for(const structure of Object.keys(adapters)){const state={nodes:[{id:'a',value:1,state:'active',row:0,col:0},{id:'b',value:2,state:'idle',row:1,col:0}],edges:[{id:'ab',from:'a',to:'b',directed:true}]};const result=layout(state,structure);assert.equal(result.positions.size,2);assert([...result.positions.values()].flat().every(Number.isFinite));}
const {sortingTraces}=load('compare');for(const input of [[],[1],[3,2,1],[5,2,8,1],[-5,2,-1,0],[4,4,1,4]])for(const frames of Object.values(sortingTraces(input)))assert.deepEqual(frames.at(-1).values,[...input].sort((a,b)=>a-b));assert.equal(sortingTraces([5,2,8,1]).bubble.at(-1).swaps,4);console.log('PASS snapshot compiler, exact code anchors, 17 structure layouts, sorting comparisons and final states');
