import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { applyVisualizerProgress, visualizerKey, latestVisualizer } from '../src/services/visualizerProgress';
import type { LearningProgress } from '../src/types/user';
import { activeLearningSeconds } from '../src/services/progressActivity';

assert.equal(activeLearningSeconds(0,1000,0,true),1);
assert.equal(activeLearningSeconds(0,1000,0,false),0,'background/hidden time excluded');
assert.equal(activeLearningSeconds(59900,60900,0,true),0.1,'only time before idle threshold counts');
assert.equal(activeLearningSeconds(61000,62000,0,true),0,'idle time excluded');
assert.equal(activeLearningSeconds(0,120000,0,true),0,'sleep/suspended time excluded');
const routes = [...readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8').matchAll(/<Route path="([^"]+)"/g)].map(m => m[1]);
assert.equal(new Set(routes).size,routes.length,'each public URL has one declaration');
for(const route of ['/learn','/learn/data-structures','/learn/algorithms','/video-learning','/3d-visualizer','/algorithms-visualizer','/coding','/quiz','/profile']) assert(routes.includes(route));

const old: LearningProgress = {userId:'learner',topics:[],totalTimeSpentMinutes:0,overallScore:0,streak:0,badges:[],weakAreas:[],recommendedTopics:[],totalXp:42};
let progress = applyVisualizerProgress(old,{name:'Heap',variant:'Max Heap',totalSteps:5,step:0});
assert.equal(old.visualizerModules,undefined);
assert.equal(progress.topics[0].status,'in-progress');
for(let step=1;step<5;step++) progress=applyVisualizerProgress(progress,{name:'Heap',variant:'Max Heap',totalSteps:5,step});
const key=visualizerKey('Heap','Max Heap');
assert.equal(progress.visualizerModules![key].completed,false,'tour alone is insufficient');
progress=applyVisualizerProgress(progress,{name:'Heap',variant:'Max Heap',totalSteps:5,inspected:'root'});
assert.equal(progress.visualizerModules![key].completed,false,'heap requires an operation');
progress=applyVisualizerProgress(progress,{name:'Heap',variant:'Max Heap',totalSteps:5,operation:'insert',seconds:12});
assert.equal(progress.visualizerModules![key].completed,true);
const activity=structuredClone(progress.dailyActivity);
progress=applyVisualizerProgress(progress,{name:'Heap',variant:'Max Heap',totalSteps:5,step:4});
assert.deepEqual(progress.dailyActivity,activity,'completion activity is idempotent');
assert.equal(progress.totalXp,42,'no invented or repeated XP');
assert.equal(progress.totalTimeSpentMinutes,0.2);
assert.equal(progress.topics[0].completionPercent,0);
assert.equal(progress.topics[0].status,'in-progress');
progress=applyVisualizerProgress(progress,{name:'Heap',variant:'Min Heap',totalSteps:5,step:2,reducedMotion:true});
assert.equal(progress.visualizerModules![key].currentStep,4,'variant progress is independent');
assert.equal(latestVisualizer(progress,'Heap')?.variant,'Min Heap');
for(const name of ['BST','AVL Tree','Binary Tree']) progress=applyVisualizerProgress(progress,{name,variant:name,totalSteps:2,step:0});
assert.equal(progress.topics.filter(t=>t.topicId==='binary-tree').length,1);
assert.equal(progress.topics.some(t=>t.topicId==='avl-tree'||t.topicId==='bst'),false);
progress=applyVisualizerProgress(progress,{name:'Array',variant:'Static Array',totalSteps:2,step:0});
progress=applyVisualizerProgress(progress,{name:'Array',variant:'Static Array',totalSteps:2,step:1,inspected:'cell:0'});
assert.equal(progress.visualizerModules![visualizerKey('Array','Static Array')].completed,true);
const reload=JSON.parse(JSON.stringify(progress));
assert.equal(reload.visualizerReducedMotion,true);
assert.equal(reload.visualizerModules[key].completed,true);
assert.equal(reload.visualizerModules[key].timeSpentSeconds,12);
console.log('PASS old data, start, tour, interaction requirements, completion, idempotency, XP, time, variants, canonical BST/AVL mapping, serialization.');
