import {useRef,useEffect,useMemo,useState} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Html,Line,Stars} from '@react-three/drei';
import * as THREE from 'three';
import {createPlanetTexture,createRadialGlowTexture} from '../components/planetTextures';
import {topics,type UniverseTopic} from './model';
function Camera({selected,reset,reduced}:{selected:string|null;reset:number;reduced:boolean}){const {camera,invalidate}=useThree();const controls=useRef<any>(null);const target=useRef(new THREE.Vector3());const destination=useRef(new THREE.Vector3(0,10,14));const moving=useRef(false);const previousReset=useRef(reset);
useEffect(()=>{const resetting=reset!==previousReset.current;previousReset.current=reset;const t=resetting?undefined:topics.find(t=>t.id===selected);target.current.set(t?t.position[0]*.15:0,.8,t?t.position[2]*.15:0);destination.current.set(t?t.position[0]*.12:0,10,14);moving.current=true;invalidate()},[selected,reset,invalidate]);
useFrame((_,dt)=>{if(!moving.current||!controls.current)return;const speed=reduced?1:1-Math.exp(-dt*10);camera.position.lerp(destination.current,speed);controls.current.target.lerp(target.current,speed);controls.current.update();if(camera.position.distanceTo(destination.current)<.01&&controls.current.target.distanceTo(target.current)<.01)moving.current=false;else invalidate()});return <OrbitControls ref={controls} enablePan={false} minDistance={12} maxDistance={23} minPolarAngle={.35} maxPolarAngle={1.2} minAzimuthAngle={-.75} maxAzimuthAngle={.75} onStart={()=>{moving.current=false}} enableDamping={!reduced}/>;}
function Node({topic,selected,match,related,percent,onSelect}:{topic:UniverseTopic;selected:boolean;match:boolean;related:boolean;percent:number;onSelect:(id:string)=>void}){const [hovered,setHovered]=useState(false);const opacity=match?(related?1:.65):.2;const surface=useMemo(()=>createPlanetTexture(topic.id,topic.color,topic.secondaryColor),[topic.id,topic.color,topic.secondaryColor]);const glow=useMemo(()=>createRadialGlowTexture(topic.color),[topic.color]);useEffect(()=>()=>{surface.dispose();glow.dispose()},[surface,glow]);return <group position={topic.position} scale={selected?1.07:1}><mesh onClick={()=>onSelect(topic.id)} onPointerOver={()=>setHovered(true)} onPointerOut={()=>setHovered(false)}><sphereGeometry args={[.52,32,24]}/><meshStandardMaterial map={surface} color="#ffffff" emissive={topic.color} emissiveIntensity={match?((selected||hovered)?.65:.25):.03} transparent opacity={opacity} metalness={.4} roughness={.35}/></mesh><sprite scale={[2.5,2.5,1]}><spriteMaterial map={glow} transparent opacity={match?1:.15} depthWrite={false} blending={THREE.AdditiveBlending}/></sprite><mesh rotation={[1.18,.2,.3]}><torusGeometry args={[.72,.025,8,64]}/><meshBasicMaterial color={topic.color} transparent opacity={match?.85:.1}/></mesh>{selected&&<mesh><sphereGeometry args={[.61,24,16]}/><meshBasicMaterial color={topic.color} transparent opacity={.08} side={THREE.BackSide}/></mesh>}<Html position={[.68,.25,0]} style={{opacity}}><button className="uv-node-label" onClick={()=>onSelect(topic.id)} title={`${topic.name}: ${percent}% complete, ${topic.lessons} lessons`} aria-label={`Focus ${topic.name}`}><strong>{topic.name}</strong><span style={{borderColor:topic.color,color:topic.color}}>{percent===100?'✓ Completed':percent>0?`${percent}% · In progress`:`${topic.lessons} lessons`}</span></button></Html></group>}
export default function UniverseScene({selected,onSelect,matches,progress,reset,reduced}:{selected:string|null;onSelect:(id:string)=>void;matches:string[];progress:Record<string,number>;reset:number;reduced:boolean}){return <Canvas camera={{position:[0,10,14],fov:38}} dpr={[1,1.5]} frameloop="demand"><color attach="background" args={['#050d1c']}/><ambientLight intensity={.65}/><directionalLight position={[-4,7,5]} intensity={2} color="#b7d6ff"/><pointLight position={[0,3,1]} intensity={8} color="#716cff"/><Stars radius={45} depth={12} count={700} factor={2} saturation={.2} fade speed={0}/><group><mesh><icosahedronGeometry args={[1.9,3]}/><meshStandardMaterial color="#2934b9" emissive="#27217e" emissiveIntensity={.4} roughness={.35} metalness={.5} flatShading/></mesh><mesh rotation={[1.12,.25,.45]}><torusGeometry args={[2.2,.035,12,96]}/><meshBasicMaterial color="#af92ff"/></mesh><mesh rotation={[1.5,-.4,-.3]}><torusGeometry args={[2.35,.016,8,96]}/><meshBasicMaterial color="#ffce84"/></mesh><Html center position={[0,.25,1.6]} style={{pointerEvents:"none"}}><div className="uv-core">Data<br/>Structures<small>The building blocks<br/>of efficient programs</small></div></Html></group>{[3,4.6,5.8].map((r,i)=><Line key={r} points={Array.from({length:100},(_,j)=>{const a=j/99*Math.PI*2;return [Math.cos(a)*r,-.2,Math.sin(a)*r] as [number,number,number]})} color={['#3269a8','#806045','#533bb1'][i]} lineWidth={.65}/>)}{topics.map(t=><Node key={t.id} topic={t} selected={selected===t.id} match={matches.includes(t.id)} related={!selected||selected===t.id||t.prerequisites.includes(selected)||topics.find(n=>n.id===selected)?.group===t.group} percent={progress[t.id]} onSelect={onSelect}/>)}<Camera selected={selected} reset={reset} reduced={reduced}/></Canvas>}

