import {useCallback,useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {BookOpen,Video,Clock,FileText,NotebookPen,Code2,Box,Sparkles,Download,ArrowRight,CheckCircle2,Circle,Copy,Plus,Trash2} from 'lucide-react';
import useAuthStore from '../../stores/useAuthStore';
import useProgressStore from '../../stores/useProgressStore';
import type {VideoLessonProgress} from '../../types/user';
import {useTutor} from '../ai-tutor/useTutor';
import TutorMarkdown from '../ai-tutor/TutorMarkdown';
import {StructurePreview} from '../learn/catalog/StructurePreview';
import {lessons,topicIds,topicNames,formatTime} from './lessons';
import {languages,codeExample,type ExampleLanguage} from './examples';
import VideoLessonPlayer from './VideoLessonPlayer';
import './video-learning.css';
const tabs=[['Transcript',FileText],['Notes',NotebookPen],['Code Examples',Code2],['Resources',Box],['Ask AI',Sparkles]] as const;
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function VideoLearningPage(){
 const [params,setParams]=useSearchParams();const lesson=lessons.find(l=>l.id===params.get('lesson'))||lessons[0];const index=lessons.indexOf(lesson);const next=lessons[index+1];
 const owner=useAuthStore(s=>s.user?.id||'guest'),raw=useProgressStore(s=>s.progress),saveLesson=useProgressStore(s=>s.saveVideoLesson);const records=raw?.userId===owner?raw.videoLessons||{}:{};const saved=records[lesson.id];
 const [syllabusOpen,setSyllabusOpen]=useState(false);const video=useRef<HTMLVideoElement>(null);const [time,setTime]=useState(0),[durations,setDurations]=useState<Record<string,number>>({}),[tab,setTab]=useState('Transcript'),[language,setLanguage]=useState<ExampleLanguage>('Python'),[question,setQuestion]=useState(''),[notice,setNotice]=useState('');const tutor=useTutor();
 const save=useCallback((patch:Partial<VideoLessonProgress>)=>{void saveLesson(lesson.id,patch,owner,topicIds[lesson.id])},[lesson.id,owner,saveLesson]);
 useEffect(()=>{setTime(0);setNotice('')},[lesson.id]);
 useEffect(()=>{const videos=lessons.map(l=>{const v=document.createElement('video');v.preload='metadata';v.onloadedmetadata=()=>setDurations(d=>({...d,[l.id]:v.duration}));v.src=l.videoUrl;return v});return()=>videos.forEach(v=>{v.onloadedmetadata=null;v.removeAttribute('src');v.load()})},[]);
 const completed=lessons.filter(l=>records[l.id]?.completed).length;const percent=Math.round(completed/lessons.length*100);const duration=durations[lesson.id]||saved?.duration||0;const transcript=lesson.transcript||[];const activeSegment=transcript.filter(t=>t.time<=time).at(-1);const notes=saved?.notes||[];
 function select(id:string){video.current?.pause();setParams({lesson:id});setTab('Transcript')}
 function seek(n:number){if(video.current)video.current.currentTime=Math.min(n,video.current.duration||n)}
 function ask(text=question){if(!text.trim()||tutor.busy)return;setTab('Ask AI');setQuestion('');tutor.send(`Lesson: ${lesson.title}. Topic: ${topicNames[lesson.id]}. Playback position: ${formatTime(time)}. ${activeSegment?'Current transcript: '+activeSegment.text:'Lesson summary: '+lesson.summary.join(' ')}\n\nStudent question: ${text.trim()}`)}
 return <div className="vl-page"><div className="vl-main"><header className="vl-heading"><nav aria-label="Breadcrumb"><Link to="/learn">Learn</Link><span>›</span><Link to="/video-learning">Video Lessons</Link><span>›</span><Link to={`/learn/${topicIds[lesson.id]}`}>{topicNames[lesson.id]}</Link><span>›</span><span>{lesson.title}</span></nav><div className="vl-title"><span><Video/></span><div><h1>{lesson.title}</h1><p>{lesson.description}</p><div className="vl-badges"><span>{topicNames[lesson.id]}</span><span className="green">{['arrays','linked-lists','queues'].includes(lesson.id)?'Beginner':'Intermediate'}</span><span><Clock size={11}/>{duration?formatTime(duration):'Loading duration…'}</span><span><Video size={11}/>Video Lesson</span></div></div></div><div className="vl-heading-art" aria-hidden="true"><StructurePreview type={topicIds[lesson.id]} color="#5148d9" title=""/></div></header>
 <VideoLessonPlayer key={`${owner}-${lesson.id}`} lesson={lesson} saved={saved} videoRef={video} onSave={save} onTime={setTime} onDuration={n=>setDurations(d=>({...d,[lesson.id]:n}))}/>
 {(saved?.position||0)>0&&!saved?.completed&&<p className="vl-resume">Resuming your lesson from {formatTime(saved!.position)}.</p>}
 <div className="vl-tabs" role="tablist" aria-label="Lesson tools">{tabs.map(([name,Icon],i)=><button role="tab" key={name} id={`vl-tab-${i}`} aria-controls="vl-tab-panel" aria-selected={tab===name} tabIndex={tab===name?0:-1} onClick={()=>setTab(name)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?4:(i+(e.key==='ArrowRight'?1:4))%5;setTab(tabs[n][0]);document.getElementById(`vl-tab-${n}`)?.focus()}}}><Icon size={16}/>{name}</button>)}</div>
 <section className="vl-panel vl-tools" role="tabpanel" id="vl-tab-panel" aria-labelledby={`vl-tab-${tabs.findIndex(t=>t[0]===tab)}`}>
 {tab==='Transcript'&&<><header><h2><FileText/>Lesson Transcript</h2>{transcript.length>0&&<button onClick={()=>download(`${lesson.id}-transcript.txt`,transcript.map(t=>formatTime(t.time)+' '+t.text).join('\n'))}><Download size={14}/>Download</button>}</header>{transcript.length?transcript.map((t,i)=><div key={i} className={`vl-transcript-line ${activeSegment===t?'active':''}`}><button onClick={()=>seek(t.time)}>{formatTime(t.time)}</button><p>{t.text}</p></div>):<><p className="vl-muted">Transcript is being prepared. Check back shortly.</p><h3>Lesson summary</h3><div className="vl-summary">{lesson.summary.map((s,i)=><p key={s}><span>{i+1}</span>{s}</p>)}</div></>}</>}
 {tab==='Notes'&&<><header><h2><NotebookPen/>My Notes</h2><button onClick={()=>save({notes:[...notes,{id:crypto.randomUUID(),time,text:'',createdAt:new Date().toISOString()}]})}><Plus size={14}/>Add Note</button></header><p className="vl-muted">Notes save automatically on this device.</p>{!notes.length&&<p>Add a note to remember an idea or question.</p>}{notes.map(n=><div className="vl-note" key={n.id}><button onClick={()=>seek(n.time)}>{formatTime(n.time)}</button><textarea aria-label={`Note at ${formatTime(n.time)}`} value={n.text} onChange={e=>save({notes:notes.map(item=>item.id===n.id?{...item,text:e.target.value}:item)})}/><button aria-label="Delete note" onClick={()=>save({notes:notes.filter(item=>item.id!==n.id)})}><Trash2 size={15}/></button></div>)}</>}
 {tab==='Code Examples'&&<><header><h2><Code2/>Code Examples</h2><select aria-label="Code language" value={language} onChange={e=>setLanguage(e.target.value as ExampleLanguage)}>{languages.map(l=><option key={l}>{l}</option>)}</select><button onClick={()=>navigator.clipboard.writeText(codeExample(lesson.id,language)).then(()=>setNotice('Code copied.')).catch(()=>setNotice('Copy unavailable. Select the code to copy it.'))}><Copy size={14}/>Copy</button></header><pre>{codeExample(lesson.id,language)}</pre><Link className="vl-resource" to="/workspace?tab=code" state={{lessonCode:codeExample(lesson.id,language),lessonLanguage:({'Python':'python','JavaScript':'javascript','Java':'java','C++':'cpp'} as const)[language]}}>Open in Playground <ArrowRight size={15}/></Link></>}
 {tab==='Resources'&&<><header><h2><Box/>Lesson Resources</h2></header><button className="vl-resource" onClick={()=>download(`${lesson.id}-summary.txt`,lesson.title+'\n\n'+lesson.summary.join('\n\n')+'\n\n'+codeExample(lesson.id,'Python'))}>Download summary & example <Download size={15}/></button><Link className="vl-resource" to={`/learn/${topicIds[lesson.id]}`}>Further reading: {topicNames[lesson.id]} <BookOpen size={15}/></Link><Link className="vl-resource" to={`/3d-visualizer?ds=${encodeURIComponent(({arrays:'Array','linked-lists':'Linked List',queues:'Queue','binary-tree':'Binary Tree',hash:'Hash Table',heap:'Heap'} as Record<string,string>)[lesson.id])}`}>Related visualization <Box size={15}/></Link><Link className="vl-resource" to={`/coding?topic=${encodeURIComponent(lesson.id==='hash'?'Hash':topicNames[lesson.id])}`}>Practice problems <Code2 size={15}/></Link></>}
 {tab==='Ask AI'&&<><header><h2><Sparkles/>Ask Alvio AI Tutor</h2><Link to="/ai-tutor">Open AI Tutor →</Link></header><div className="vl-ai-prompts">{['Explain this more simply.','Give me an example in Python.','Quiz me on this topic.'].map(q=><button key={q} disabled={tutor.busy} onClick={()=>ask(q)}>{q}</button>)}</div><div className="vl-ai-messages">{tutor.chat.messages.map(m=><div key={m.id} className={m.role}><strong>{m.role==='user'?'You':'Alvio AI'}</strong><TutorMarkdown text={m.role==='user'?m.content.split('Student question: ')[1]||m.content:m.content}/></div>)}</div>{tutor.busy&&<p role="status">Thinking… <button onClick={tutor.stop}>Stop</button></p>}{tutor.error&&<p role="alert">AI assistance is temporarily unavailable. Your video lesson is still available. <button onClick={tutor.retry}>Retry</button></p>}</>}
 <form className="vl-question" onSubmit={e=>{e.preventDefault();ask()}}><Sparkles size={18}/><input aria-label="Ask a question about this lesson" placeholder="Ask a question about this lesson…" value={question} onChange={e=>setQuestion(e.target.value)}/><button aria-label="Send lesson question" disabled={!question.trim()||tutor.busy}><ArrowRight size={20}/></button></form>{notice&&<p role="status">{notice}</p>}
 </section></div>
 <aside className="vl-sidebar"><section className="vl-panel vl-progress"><h2>Lesson Progress</h2><div><div className="vl-ring" style={{background:`conic-gradient(#05ceb4 ${percent}%,#102953 0)`}}><strong>{completed}/{lessons.length}</strong></div><div><p>{completed} of {lessons.length} lessons completed</p><div className="vl-progress-bar"><progress max="100" value={percent}/><span>{percent}%</span></div><button disabled={saved?.completed} onClick={()=>save({completed:true})}>{saved?.completed?'Completed':'Mark as Complete'}<CheckCircle2 size={16}/></button></div></div>{duration>0&&(saved?.watchedSeconds.length||0)/duration>=.9&&!saved?.completed&&<p className="vl-completion-hint">You’ve watched most of this lesson. Ready to mark it complete?</p>}</section>
 <section className={`vl-panel vl-syllabus ${syllabusOpen?'':'is-collapsed'}`}><h2>Syllabus <button className="vl-syllabus-toggle" aria-expanded={syllabusOpen} onClick={()=>setSyllabusOpen(v=>!v)}>{syllabusOpen?'Hide lessons':'Show lessons'}</button></h2>{lessons.map((l,i)=><button key={l.id} aria-current={l.id===lesson.id?'step':undefined} onClick={()=>select(l.id)}><span className="vl-number">{i+1}</span><span className="vl-thumbnail"><StructurePreview type={topicIds[l.id]} color="#448dff" title=""/></span><span><strong>{l.title}</strong><small><Clock size={11}/>{durations[l.id]?formatTime(durations[l.id]):'Loading…'}</small></span>{records[l.id]?.completed?<CheckCircle2 className="complete" size={20} aria-label="Completed"/>:<Circle size={20} aria-label="Available"/>}</button>)}</section>
 {next&&<button className="vl-panel vl-next" onClick={()=>select(next.id)}><h2>Next Lesson <ArrowRight size={15}/></h2><div><span className="vl-thumbnail"><StructurePreview type={topicIds[next.id]} color="#5f79ff" title=""/></span><span><strong>{next.title}</strong><small>{next.description}</small><small><Clock size={12}/>{durations[next.id]?formatTime(durations[next.id]):'Loading…'}</small></span><i><ArrowRight size={22}/></i></div></button>}
 </aside></div>;
}

