import {useEffect,useMemo,useRef,useState,type RefObject} from 'react';
import {Play,Pause,Volume2,VolumeX,Maximize,PictureInPicture,ClosedCaption} from 'lucide-react';
import type {VideoLessonProgress} from '../../types/user';
import {type VideoLesson,formatTime,topicIds} from './lessons';
import {StructurePreview} from '../learn/catalog/StructurePreview';
export default function VideoLessonPlayer({lesson,saved,videoRef,onSave,onTime,onDuration}:{lesson:VideoLesson;saved?:VideoLessonProgress;videoRef:RefObject<HTMLVideoElement|null>;onSave:(patch:Partial<VideoLessonProgress>)=>void;onTime:(n:number)=>void;onDuration:(n:number)=>void}){
 const frame=useRef<HTMLDivElement>(null);const [playing,setPlaying]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(false),[time,setTime]=useState(0),[duration,setDuration]=useState(saved?.duration||0),[muted,setMuted]=useState(false),[speed,setSpeed]=useState(saved?.speed||1),[captions,setCaptions]=useState(false),[notice,setNotice]=useState('');
 const watched=useRef(new Set(saved?.watchedSeconds||[]));const previous=useRef(0),lastSaved=useRef(0),saveRef=useRef(onSave);saveRef.current=onSave;const initial=useRef(saved);const initialized=useRef(false);
 const trackUrl=useMemo(()=>{if(!lesson.transcript?.length)return undefined;const stamp=(n:number)=>'00:'+formatTime(n)+'.000';const content='WEBVTT\n\n'+lesson.transcript.map((t,i)=>`${stamp(t.time)} --> ${stamp(lesson.transcript?.[i+1]?.time||duration)}\n${t.text}\n`).join('\n');return URL.createObjectURL(new Blob([content],{type:'text/vtt'}))},[lesson.transcript,duration]);
 useEffect(()=>()=>{if(trackUrl)URL.revokeObjectURL(trackUrl)},[trackUrl]);
 function save(){const v=videoRef.current;if(initialized.current&&v&&Number.isFinite(v.duration))saveRef.current({position:v.currentTime,duration:v.duration,speed:v.defaultPlaybackRate,watchedSeconds:[...watched.current]})}
 useEffect(()=>{const v=videoRef.current;const unload=()=>save();window.addEventListener('pagehide',unload);return()=>{window.removeEventListener('pagehide',unload);if(initialized.current&&v&&Number.isFinite(v.duration))saveRef.current({position:v.currentTime,duration:v.duration,speed:v.defaultPlaybackRate,watchedSeconds:[...watched.current]})}},[]);
 function restore(){if(initialized.current)return;const v=videoRef.current!;setDuration(v.duration);onDuration(v.duration);v.defaultPlaybackRate=initial.current?.speed||1;v.playbackRate=v.defaultPlaybackRate;if((initial.current?.position||0)<v.duration-.25)v.currentTime=initial.current?.position||0;previous.current=v.currentTime;initialized.current=true;setReady(v.readyState>=3);setTime(v.currentTime);onTime(v.currentTime)}
 useEffect(()=>{if(videoRef.current&&videoRef.current.readyState>=1)restore()},[]);
 function toggle(){const v=videoRef.current;if(!v)return;if(v.paused)v.play().catch(()=>setNotice('Press play to start this lesson.'));else v.pause()}
 function fullscreen(){const el=frame.current;if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else el?.requestFullscreen().catch(()=>setNotice('Fullscreen is unavailable in this browser.'))}
 function seek(n:number){const v=videoRef.current;if(initialized.current&&v&&Number.isFinite(v.duration)){v.currentTime=Math.max(0,Math.min(v.duration,n));previous.current=v.currentTime;save()}}
 function caption(){if(!trackUrl){setNotice('Captions are being prepared.');return}const v=videoRef.current;if(v?.textTracks[0])v.textTracks[0].mode=captions?'hidden':'showing';setCaptions(!captions)}
 return <div className="vl-player" ref={frame} tabIndex={0} role="region" aria-label="Lesson video player" onKeyDown={e=>{if(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,button,a'))return;const v=videoRef.current;if(!v)return;if([' ','arrowleft','arrowright','m','f','c'].includes(e.key.toLowerCase()))e.preventDefault();switch(e.key.toLowerCase()){case ' ':toggle();break;case 'arrowleft':seek(v.currentTime-5);break;case 'arrowright':seek(v.currentTime+5);break;case 'm':v.muted=!v.muted;setMuted(v.muted);break;case 'f':fullscreen();break;case 'c':caption();break}}}>
 <video ref={videoRef} src={lesson.videoUrl} playsInline preload="metadata" onLoadedMetadata={restore} onCanPlay={()=>setReady(true)} onWaiting={()=>setReady(false)} onError={()=>{setError(true);setReady(false)}} onPlay={()=>setPlaying(true)} onPause={()=>{setPlaying(false);save()}} onEnded={()=>{setPlaying(false);save()}} onSeeking={()=>{previous.current=videoRef.current?.currentTime||0}} onTimeUpdate={()=>{const v=videoRef.current!;const n=v.currentTime;if(!v.paused&&!v.seeking&&n>=previous.current&&n-previous.current<=2*v.playbackRate){for(let s=Math.floor(previous.current);s<Math.min(Math.floor(n),Math.ceil(v.duration));s++)watched.current.add(s)}previous.current=n;setTime(n);onTime(n);if(Math.abs(n-lastSaved.current)>3){save();lastSaved.current=n}}}>{trackUrl&&<track src={trackUrl} kind="captions" srcLang="en" label="English"/>}</video>
 {!ready&&!error&&<div className="vl-video-loading"><StructurePreview type={topicIds[lesson.id]} color="#477dff" title={lesson.title}/><span>Loading lesson…</span></div>}
 {error&&<div className="vl-video-error"><p>This lesson couldn’t be loaded.</p><button onClick={()=>{setError(false);videoRef.current?.load()}}>Retry</button></div>}
 <div className="vl-player-top"><span>◭ Alvio</span><span>Video Lesson</span><label><span className="vl-sr">Playback speed</span><select aria-label="Playback speed" value={speed} onChange={e=>{const n=Number(e.target.value);setSpeed(n);if(videoRef.current){videoRef.current.defaultPlaybackRate=n;videoRef.current.playbackRate=n;}save()}}>{[.5,.75,1,1.25,1.5,2].map(n=><option key={n} value={n}>{n.toFixed(2)}x</option>)}</select></label></div>
 {!playing&&ready&&!error&&<button className="vl-big-play" onClick={toggle} aria-label="Play lesson"><Play size={32} fill="currentColor"/></button>}
 <div className="vl-controls"><input aria-label="Seek video" type="range" min="0" max={duration||1} step="0.1" value={Math.min(time,duration||1)} onChange={e=>seek(Number(e.target.value))}/><div><button onClick={toggle} aria-label={playing?'Pause':'Play'}>{playing?<Pause/>:<Play/>}</button><span className="vl-time">{formatTime(time)} / {formatTime(duration)}</span><button onClick={()=>{const v=videoRef.current;if(v){v.muted=!v.muted;setMuted(v.muted)}}} aria-label={muted?'Unmute':'Mute'}>{muted?<VolumeX/>:<Volume2/>}</button><button aria-label={trackUrl?'Toggle captions':'Captions unavailable'} aria-pressed={captions} onClick={caption}><ClosedCaption/></button>{'pictureInPictureEnabled' in document&&<button aria-label="Picture in picture" onClick={()=>{const v=videoRef.current;if(v) (document.pictureInPictureElement?document.exitPictureInPicture():v.requestPictureInPicture()).catch(()=>setNotice('Mini-player is unavailable in this browser.'))}}><PictureInPicture/></button>}<button onClick={fullscreen} aria-label="Fullscreen"><Maximize/></button></div></div>{notice&&<button className="vl-player-notice" onClick={()=>setNotice('')}>{notice}</button>}
 </div>;
}
