import {lazy,Suspense,useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {Activity,ArrowLeft,BookOpen,Clock,Database,Code2,Layers,Divide,RotateCcw,Mouse,BarChart3} from 'lucide-react';
import {curves,value,height,format,algorithms,type Mode} from './complexity/data';
import './catalog/data-structures.css';
import './complexity/style.css';
const Graph=lazy(()=>import('./complexity/Graph'));
const guides=[{title:'Loops (Sequential)',text:'Scanning elements sequentially runs in O(N) linear time.',Icon:Code2,code:'for (let i = 0; i < n; i++) {\n  visit(i);\n}\n// N visits; O(1) auxiliary space'}, {title:'Nested Loops',text:'Scanning every pair via nested loops runs in O(N²) quadratic time.',Icon:Layers,code:'for (let i = 0; i < n; i++)\n  for (let j = 0; j < n; j++)\n    visit(i, j);\n// N² visits; O(1) auxiliary space'}, {title:'Halving Spaces',text:'Dividing search ranges iteratively runs in O(log N) logarithmic time.',Icon:Divide,code:'while (n > 1) {\n  n = Math.floor(n / 2);\n}\n// O(log N) time; O(1) space'}];
export default function Complexity3DPage(){
const [mode,setMode]=useState<Mode>('time'),[n,setN]=useState(60),[visible,setVisible]=useState(curves.map(c=>c.id)),[selected,setSelected]=useState<string|null>(null),[hover,setHover]=useState<string|null>(null),[view,setView]=useState(()=>matchMedia('(max-width: 700px)').matches?'2d':'3d'),[reset,setReset]=useState(0),[guide,setGuide]=useState<number|null>(null),[explore,setExplore]=useState(false),[algorithm,setAlgorithm]=useState('');
const [playing,setPlaying]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches);
useEffect(()=>{const svg=document.querySelector<SVGSVGElement>('.cx-plot>svg');if(svg){if(playing)svg.unpauseAnimations();else svg.pauseAnimations()}},[playing,view]);
useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{if(media.matches)setPlaying(false)};media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
const chosen=curves.find(c=>c.id===selected),tip=curves.find(c=>c.id===hover),a=algorithms.find(a=>a.name===algorithm);
function select(id:string){setSelected(id);setAlgorithm(curves.find(c=>c.id===id)?.example||'');}
function toggle(id:string){select(id);setVisible(v=>v.includes(id)?v.length>1?v.filter(x=>x!==id):v:[...v,id]);}
return <main className="cx-page"><header className="cx-header"><Link to="/learn" className="cx-back" aria-label="Back to Learn"><ArrowLeft/></Link><div className="cx-title"><h1><Activity/>3D Complexity Analyzer</h1><span>Interactive View Mode</span><p>Explore how different algorithms scale in three dimensions.</p></div><div className="cx-controls"><div className="cx-segment">{(['time','space'] as Mode[]).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>{setMode(m);setHover(null)}}>{m==='time'?<Clock size={16}/>:<Database size={16}/>} {m==='time'?'Time':'Space'}</button>)}</div><select aria-label="Show complexity curves" value={visible.length===1?visible[0]:'all'} onChange={e=>{setVisible(e.target.value==='all'?curves.map(c=>c.id):[e.target.value]);if(e.target.value!=='all')select(e.target.value)}}><option value="all">Show All Curves</option>{curves.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><label className="cx-slider">Input Size (N) <strong>{n}</strong><input type="range" min="1" max="100" value={n} onChange={e=>setN(+e.target.value)}/></label></div></header>
<div className="cx-viewbar"><div>{[['3d','3D View'],['2d','2D Accessible View'],['table','Table View']].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</div><button aria-pressed={playing} onClick={()=>setPlaying(p=>!p)}>{playing?'Pause animation':'Play animation'}</button><button onClick={()=>setReset(r=>r+1)}><RotateCcw size={13}/>Reset view</button></div>
<section className="cx-explore" aria-label="Complexity growth visualization"><div className="cx-plot">{view==='3d'?<Suspense fallback={<p>Loading 3D graph…</p>}><Graph n={n} mode={mode} visible={visible} selected={selected} onSelect={select} onHover={setHover} reset={reset} playing={playing}/></Suspense>:view==='2d'?<svg className={playing?"cx-animated":"cx-paused"} viewBox="0 0 800 390" role="img" aria-label={`${mode==='time'?'Operations':'Storage units'} on a logarithmic scale by input size`}><text x="65" y="20">{mode==='time'?'Operations':'Storage units'} (log₁₀)</text>{[0,2,4,6].map(t=><g key={t}><path d={`M65 ${335-t*48}H715`} stroke="#203653"/><text x="15" y={340-t*48}>10^{t}</text></g>)}<path d="M65 35V335H720" fill="none" stroke="#97b6d8"/>{[1,20,40,60,80,100].map(t=><text key={t} x={65+t*6} y="355">{t}</text>)}<text x="340" y="380">Input Size (N)</text>{curves.filter(c=>visible.includes(c.id)).map(c=><g key={c.id} onMouseEnter={()=>setHover(c.id)} onMouseLeave={()=>setHover(null)} onClick={()=>select(c.id)}><path id={`cx-path-${c.id}`} d={Array.from({length:100},(_,i)=>{const x=1+(n-1)*i/99;return `${i?'L':'M'}${65+x*6},${335-height(value(c,x,mode))*48}`}).join(' ')} fill="none" stroke={c.color} strokeWidth={selected===c.id?5:2.5}/><circle className="cx-traveler" r="5" fill={c.color}><animateMotion dur="6s" repeatCount="indefinite"><mpath href={`#cx-path-${c.id}`}/></animateMotion></circle><circle cx={65+n*6} cy={335-height(value(c,n,mode))*48} r="5" fill={c.color}/><text x={75+n*6} y={335-height(value(c,n,mode))*48-curves.indexOf(c)*3} fill={c.color}>{c.label}</text></g>)}</svg>:<div className="cx-table"><table><caption>{mode==='time'?'Operation counts':'Storage units'} — representative growth models</caption><thead><tr><th>Complexity</th>{[10,20,50,n].map((x,i)=><th key={i}>N={x}</th>)}</tr></thead><tbody>{curves.filter(c=>visible.includes(c.id)).map(c=><tr key={c.id}><th><button onClick={()=>select(c.id)}>{c.label}</button></th>{[10,20,50,n].map((x,i)=><td key={i}>{format(value(c,x,mode))}</td>)}</tr>)}</tbody></table></div>}{tip&&<div className="cx-tooltip" role="status"><strong style={{color:tip.color}}>{tip.label}</strong><br/>N = {n}<br/>{mode==='time'?'Operations':'Storage units'} ≈ {format(value(tip,n,mode))}</div>}<p className="cx-scale">Logarithmic height · capped at 10⁶ · full values in Table View. Depth separates classes, not another input variable.</p></div><aside className="cx-legend"><h2>Complexity Curves</h2>{curves.map(c=><div className="cx-legend-row" key={c.id}><button aria-label={`Select ${c.label}`} aria-pressed={selected===c.id} onClick={()=>{select(c.id);setVisible(v=>v.includes(c.id)?v:[...v,c.id])}}><i style={{background:c.color}}/>{c.label}<small>{c.category}</small></button><input type="checkbox" aria-label={`Show ${c.label}`} checked={visible.includes(c.id)} onChange={()=>toggle(c.id)}/></div>)}<p><Mouse size={17}/>Drag to rotate · Scroll to zoom</p></aside></section>
<div className="cx-bottom"><section className="cx-panel"><header><BookOpen/><div><h2>Calculation Guide</h2><p>Understand how common code patterns map to time complexity.</p></div><button onClick={()=>setGuide(guide===null?0:null)}>Learn More →</button></header><div className="cx-guides">{guides.map((g,i)=><button key={g.title} aria-expanded={guide===i} onClick={()=>setGuide(guide===i?null:i)}><g.Icon/><strong>{g.title}</strong><span>{g.text}</span></button>)}</div>{guide!==null&&<pre>{guides[guide].code}</pre>}</section>
<section className="cx-panel"><header><BarChart3/><div><h2>Compare Algorithms</h2><p>Select an algorithm to inspect its time and space complexity breakdown.</p></div><button aria-expanded={explore} onClick={()=>setExplore(!explore)}>✦ Explore</button></header>{(explore||chosen)&&<label className="cx-algorithm">Algorithm <select aria-label="Compare algorithm" value={algorithm} onChange={e=>setAlgorithm(e.target.value)}><option value="">Choose an algorithm</option>{algorithms.map(a=><option key={a.name}>{a.name}</option>)}</select></label>}<div className="cx-cases">{(mode==='time'?['Best Case','Average Case','Worst Case']:['Auxiliary Space']).map((label,i)=><div key={label}><small>{label}</small><strong>{a?(mode==='time'?[a.best,a.avg,a.worst][i]:a.space):'—'}</strong></div>)}{a&&mode==='time'&&<div><small>Space</small><strong>{a.space}</strong></div>}</div><p className="cx-detail">{a?a.note:'Choose a curve from the graph or legend to see detailed analysis here.'}</p>{chosen&&<p className="cx-detail"><strong style={{color:chosen.color}}>{chosen.label} at N={n}: {format(value(chosen,n,mode))} {mode==='time'?'operations':'storage units'}</strong><br/>{mode==='space'?chosen.spaceExample:chosen.example}. Growth models illustrate scaling, not measured runtime or bytes. {mode==='space'?'Space counts retained items or stack frames; logarithmic levels are rounded up to whole frames.':''}</p>}</section></div></main>;
}
