import { Link, useLocation } from 'react-router-dom';
import { BookOpen, Box, Code2, HelpCircle } from 'lucide-react';
import { structures } from '../features/learn/catalog/structureCatalog';
import { algorithms } from '../features/learn/algorithms/model';
import useProgressStore from '../stores/useProgressStore';
import { visualizerTopics } from '../services/visualizerProgress';

export function topicNavigation(path:string){
 const structure=structures.find(s=>s.route===path), algorithm=algorithms.find(a=>a.lessonRoute===path);
 if(structure){const name=structure.title, quiz=visualizerTopics[name]?.quiz;return {name,parent:'/learn/data-structures',parentLabel:'Data Structures',lesson:path,visualize:`/3d-visualizer?ds=${encodeURIComponent(name)}`,practice:`/coding?topic=${encodeURIComponent(name)}`,quiz:name==='Heap'?undefined:quiz,progressId:structure.progressId};}
 if(algorithm){const quiz=({Graph:'Graphs',Tree:'Binary Trees','Two Pointer':'Arrays'} as Record<string,string>)[algorithm.category]||algorithm.category;return {name:algorithm.name,parent:'/learn/algorithms',parentLabel:'Algorithms',lesson:path,visualize:algorithm.visualizationRoute,practice:`/coding?topic=${encodeURIComponent(algorithm.category==='Graph'?'Graph':algorithm.category)}`,quiz:['Sorting','Searching','Graphs','Binary Trees','Arrays','Dynamic Programming','Greedy','Recursion','String','Math'].includes(quiz)?quiz:undefined,progressId:algorithm.id};}
}
export function TopicOrientation(){const {pathname}=useLocation();const topic=topicNavigation(pathname);if(!topic)return null;return <div className="topic-orientation"><nav className="app-breadcrumb" aria-label="Breadcrumb"><Link to="/learn">Learn</Link><span>›</span><Link to={topic.parent}>{topic.parentLabel}</Link><span>›</span><span aria-current="page">{topic.name}</span></nav><nav className="learning-action-strip" aria-label="Topic actions"><Link to={topic.lesson} aria-current="page"><BookOpen size={16}/>Learn</Link>{topic.visualize&&<Link to={topic.visualize}><Box size={16}/>Visualize</Link>}<Link to={topic.practice}><Code2 size={16}/>Practice</Link>{topic.quiz&&<Link to={`/quiz?topic=${encodeURIComponent(topic.quiz)}`}><HelpCircle size={16}/>Quiz</Link>}</nav></div>}
export function TopicNextStep(){const {pathname}=useLocation();const topic=topicNavigation(pathname);const progress=useProgressStore(s=>s.progress);if(!topic)return null;const completed=progress?.topics.find(t=>t.topicId===topic.progressId)?.status==='completed';return <section className="topic-next-step"><h2>Next recommended step</h2><p>{completed?'Lesson completed. Put your understanding into practice.':`Continue exploring ${topic.name} with a visual example, then apply what you learn.`}</p><Link to={completed||!topic.visualize?topic.practice:topic.visualize}>{completed||!topic.visualize?`Practice ${topic.name}`:`Explore ${topic.name} in 3D`} →</Link>{topic.visualize&&!completed&&<Link to={topic.practice}>Then: practice problems →</Link>}</section>}
export function CategoryBreadcrumb(){const {pathname}=useLocation();const label=({'/learn/sorting':'Sorting','/learn/searching':'Searching','/learn/divide-conquer':'Divide and Conquer','/learn/dynamic-programming':'Dynamic Programming','/learn/greedy':'Greedy','/learn/graph-algorithms':'Graph Algorithms'} as Record<string,string>)[pathname];return <nav className="app-breadcrumb" aria-label="Breadcrumb"><Link to="/learn">Learn</Link><span>›</span><Link to="/learn/algorithms">Algorithms</Link><span>›</span><span aria-current="page">{label}</span></nav>}
