import type {Specification,Snapshot} from './model';
const initial:Snapshot={nodes:[{id:'a',value:10,state:'idle',label:'Head'},{id:'b',value:20,state:'idle'},{id:'d',value:40,state:'idle'}],edges:[{id:'ab',from:'a',to:'b',directed:true},{id:'bd',from:'b',to:'d',directed:true}]};
const s1:Snapshot={...initial,nodes:initial.nodes.map(n=>({...n,state:n.id==='b'?'active':'idle'}))};
const s2:Snapshot={...s1,nodes:[...s1.nodes,{id:'c',value:30,state:'active',label:'New node'}]};
const s3:Snapshot={nodes:[s1.nodes[0],{...s1.nodes[1],state:'visited'},{id:'c',value:30,state:'active',label:'New node'},s1.nodes[2]],edges:[initial.edges[0],{id:'bc',from:'b',to:'c',directed:true,state:'active'},{id:'cd',from:'c',to:'d',directed:true,state:'active'}]};
const s4:Snapshot={nodes:s3.nodes.map(n=>({...n,state:'visited'})),edges:s3.edges};
export const example:Specification={version:1,supported:true,title:'Linked List: Insertion at Position 3',structure:'linked-list',operation:'Insert',language:'cpp',explanation:'To insert at position 3 (zero-based index 2), traverse to the previous node. Create a node with value 30, point it to the following node, then update the previous node’s next pointer.',hint:'Find the node immediately before the insertion position. Which link must you preserve?',complexity:{time:'O(n)',space:'O(1)',why:'Finding the previous node takes up to n steps. Insertion uses one new node and a constant number of pointers.'},code:'struct Node { int value; Node* next; };\nvoid insert(Node*& head, int index, int value) {\n  Node** link = &head;\n  while (index > 0 && *link) {\n    link = &((*link)->next);\n    --index;\n  }\n  if (index != 0) return;\n  Node* node = new Node{value, nullptr};\n  node->next = *link;\n  *link = node;\n}',steps:[
{id:'1',title:'Traverse to position 2',explanation:'Start at the head. Move to the link after node 20, the insertion point for zero-based index 2.',operation:'visit',beforeState:initial,afterState:s1,codeLines:[4,5,6]},
{id:'2',title:'Create a new node (30)',explanation:'Allocate a node containing 30. It is not connected to the list yet.',operation:'insert',beforeState:s1,afterState:s2,codeLines:[9]},
{id:'3',title:'Update pointers',explanation:'Preserve the following node by setting the new node’s next link first. Then redirect the previous node’s link to the new node.',operation:'connect',beforeState:s2,afterState:s3,codeLines:[10,11]},
{id:'4',title:'Insertion complete',explanation:'The list is now 10 → 20 → 30 → 40. Every original node remains reachable from the head.',operation:'highlight',beforeState:s3,afterState:s4,codeLines:[]}],suggestions:['Delete 20 from linked list [10,20,30,40]','Reverse linked list [10,20,30,40]','Detect a cycle in a linked list','Find the middle of linked list [10,20,30,40]']};

